//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lawyers.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LawyersEntities : DbContext
    {
        public LawyersEntities()
            : base("name=LawyersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Lawyer> Lawyers { get; set; }
        public virtual DbSet<Matter> Matters { get; set; }
        public virtual DbSet<Submatter> Submatters { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
    
        public virtual ObjectResult<sp_GetAllTasks_Result> sp_GetAllTasks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllTasks_Result>("sp_GetAllTasks");
        }
    }
}
