//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lawyers.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public int LawyerID { get; set; }
        public int SubmatterID { get; set; }
        public int BillableTime { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
    
        public virtual Lawyer Lawyer { get; set; }
        public virtual Submatter Submatter { get; set; }
    }
}
